spring:
  application:
    name: demo
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  r2dbc:
    url: r2dbc:mysql://localhost:3306/testdb_spring
    username: test_db
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    repositories.bootstrap-mode: default
    properties:
      hibernate:
        globally_quoted_identifiers: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: true
server:
  port : 8080
  tomcat:
    threads:
      max: 300
management:
  info:
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    git:
      enabled: true
  endpoint:
    info:
      enabled: true
      cache:
        time-to-live: 60s
  endpoints:
    web:
      exposure:
        include: '*'
                
logging:
  level:
    root: INFO
    org.springframework: DEBUG